### ISSUE TITLE
looks good, but how to use.

### ISSUE THREAD

**Issue by g10guang** [neutaaaaan/iosvkem#1]
I am new to vim. I don't know to config.

I almost write cpp and I am going to dev on remote linux machine.

Thanks.

**Comment by neutaaaaan** [comment]
Generally speaking, I recommend reading [usr_05.txt](https://github.com/vim/vim/blob/master/runtime/doc/usr_05.txt)  if only to get a decent idea of how a .vimrc works. Vim's documentation is really good and we all ought to look it up more often than we do.

As for your particular case, it sounds like you won't have control over the machine vim will be running on, meaning you're unlikely to be able to copy files to it and will most likely stick to using fairly defaults settings : nobody wants to feed vim more than 4 or 5 commands manually before getting to work.

That said, if you do have control over the machine vim is running on, or your user account has write privileges,  you can either :

- copy [the colourscheme](https://github.com/neutaaaaan/iosvkem/blob/master/colors/Iosvkem.vim) into the relevant folder - usually `~/.vim/colors `-
- use a plugin manager such as [vim-plug](https://github.com/junegunn/vim-plug) or [vundle](https://github.com/VundleVim/Vundle.vim) 

and then add `colorscheme Iosvkem` to your .vimrc or call it from within vim with `:colorscheme Iosvkem` 

I'll add a similiar blurb to the readme later tonight.
