### ISSUE TITLE
Comments in Vim do not match background

### ISSUE THREAD

**Issue by thegeorgeliu** [neutaaaaan/iosvkem#2]
Comments in command-line Vim show with a light grey background, even when TERM=xterm-256color is set. This doesn't happen when a GUI version of Vim is used.
<img width="682" src="https://user-images.githubusercontent.com/31437427/43393718-e55b5c6a-93ac-11e8-894c-73ad976281e7.png">

**Comment by neutaaaaan** [comment]
Not familiar at all with MacOS but that looks a lot like your terminal emulator doesn't support italics.
It works fine in gnome-terminal and `echo $TERM` spits out `xterm-256color` as well.

**Comment by thegeorgeliu** [comment]
It seems like your guess about the terminal emulator not supporting italics is correct since when I change all instances of "cterm=NONE,italic" to "cterm=NONE", the light grey background goes away.

<img width="682" src="https://user-images.githubusercontent.com/31437427/43429017-0881dc46-9416-11e8-9a3a-8d7dc16d91ec.png">

**Comment by neutaaaaan** [comment]
Take a look at [this](https://hobo.house/2017/07/17/using-italics-with-vim-in-your-terminal/), that should be a decent starting point.

I'll look into making italicized comments toggleable in the near future but feel free to beat me to it :stuck_out_tongue:

**Comment by neutaaaaan** [comment]
Added a toggle, it's somewhat finnicky on my machine but that's probably down to my .vimrc being a mess. I'll close that ticket again in a couple days if no one reports issues.
