### ISSUE TITLE
Line and column highlighting is not working properly

### ISSUE THREAD

**Issue by gqst** [neutaaaaan/iosvkem#3]
I really like your theme. :)
I'm a novice. My terminal is Tilix and OS is Manjaro. 

I found that the current line does not show any effect and it just mark the text as white on the column with no background color.

As shown in the picture（My cursor is on line 50.）：
![example](http://thyrsi.com/t6/362/1535203535x-1404817880.png)

**Comment by neutaaaaan** [comment]
I just pushed a fix for both CursorColumn and CursorLine colours, set to #303030 which is the colour used for selections. Seems to work alright at first glance.
I'll leave this ticket open for a couple days / until we're done fixing my mistakes/ until you close it  - whichever comes first.

**Comment by gqst** [comment]
This problem is well solved～
