### ISSUE TITLE
Reverted colors in SignColumn when using ALE

### ISSUE THREAD

**Issue by antoniotrkdz** [neutaaaaan/iosvkem#4]
Hi,
SignColumn symbols are displayed reversed when using ALE and/or signify plugins.
Screenshots:
![image](https://user-images.githubusercontent.com/18493541/54690744-58a9b900-4b22-11e9-8939-7f4b7383bb02.png)
![image](https://user-images.githubusercontent.com/18493541/54690910-ade5ca80-4b22-11e9-9fea-b30d3c4f2b80.png)

I second that it could be intended according to what I understood skimming thru the `colors/iosvkem.vim` file, but please, it is an ugly (IMHO) spot on an otherwise cool theme.

I tried to change the highlight values for Diff{Add,Change,Delete,Text} to no avail.
I also tried to manipulate highlight of ALE{Error,Warning,etc..} but again no success.

Can it be changed?
Or at least provide an option to display these info "reverted" or "plain"?

Thanks!

**Comment by neutaaaaan** [comment]
# ALE

`ALEErrorSign` and `ALEWarningSign` inherit their behaviour from `Error` and `Todo`.  

I'm not going to override that behaviour for a few reasons :  
* It's not broken, inaccurate or misleading.
* If a user were to load such a modified version of Iosvkem first, and then load another theme during the same session, that other theme would inherit the modifications *unless* it had its own overrides.
* *I like it*
  
  
# SIGNIFY
As for vim-signify, I don't use it, but I gave its code a quick glance and it hooks into `Diff[xxx]` which if I'm not mistaken implies roughly the same behaviour as ALE.

It's arguably harder on the eyes, but I'm not willing to change how `Diff[xxx]` works, and as long as it only messes up with the gutter - not the content of the corresponding line - it's not worth thinking about overriding in the theme itself.  
Please get back to me if I'm mistaken.

### The toggles do nothing !
Nope. It's additional logic I'd have to support, and it doesn't feel justified, unlike that macos terminal issue from a while ago, as the *"proper fix"* would have required to mess about with parameters outside of vim.
    
### But don't batphone Obi-Wan just yet
The good news is that the end user can override all of that easily in their .vimrc :  
* The 2 problematic groups for ALE are `ALEErrorSign` and `ALEWarningSign`
* You can find a list of the relevant groups for vim-signify [here](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/highlight.vim#L20). 

Adding some variant of `hi group guifg=#hex guibg=#hex gui=bold cterm=bold` at the bottom of your .vimrc for each of the problematic groups should do the trick.  
You'll have to extract the right colours out of Iosvkem but I gather you can handle that.

**Comment by antoniotrkdz** [comment]
Thank for your reply.
I actually solved this!
 in .vimrc:
```vim 
if g:colors_name=='Iosvkem'
    " Fix ALE signs highlight
    hi ALEErrorSign cterm=bold ctermfg=203 gui=bold guifg=#ff2040
    hi ALEWarningSign cterm=bold ctermfg=220 gui=bold guifg=#fcbb20
    " Fix Signify highlight
    hi SignifySignAdd ctermfg=34 guifg=#40bb40
    hi SignifySignChange ctermfg=220 guifg=#fcbb20
    hi SignifySignDelete ctermfg=167 guifg=#cc4040
    "Fix git-gutter highlight
    hi GitGutterChange ctermfg=220 guifg=#fcbb20
endif
```
It turns out I was using the wrong highlight groups for ALE :confused:
At least I got a better grasp of vim highlighting...
One Note: I reverted back to vim-git-gutter and for some strange reason it shows the signs "properly" (:heart: see below) although they still inherit from `Diff[xxx]`, I only changed `GitGutterChange` to suit my tastes - speaking of which, the Latins used to say:

> *De gustibus [et coloribus] non est disputandum*

Wisely stating that *tastes are not a matter for discussion*.
Thank you once more and I will close the issue.
