### ISSUE TITLE
Just some commentary about the color values

### ISSUE THREAD

**Issue by jwortmann** [neutaaaaan/iosvkem#6]
Hi, I don't use Vim but I found your repository while searching for some of the color values in Google and I just wanted to add some comments:

In case you want to credit the "real" origin (as far as I know) in the README file; the main colors of this scheme are the colors which are used by the default dark theme in the Adobe Brackets text editor. It seems that you have added some colors (these look really great!) and adjusted some of the color values slightly, e.g. `#d08928` instead of `#d89333` for strings and `#60aa00` instead of `#85a300` for numbers. All of the original colors can be found in the Brackets repo https://github.com/adobe/brackets/blob/master/src/extensions/default/DarkTheme/main.less (and some diff colors are inherited from the [light theme](https://github.com/adobe/brackets/blob/master/src/styles/brackets_theme_default.less)) or in an [overview](https://github.com/jwortmann/brackets-color-scheme#color-palette) from a porting of the Brackets schemes for Sublime Text that I made a few years ago. There is even another purple color `#6c71c4` defined in the Brackets source file ("cm-rangeinfo"), but I was never able to find any occurrence of this color in the editor.

**Comment by neutaaaaan** [comment]
Nice catch !  
I always assumed the colours came from *somewhere* but couldn't find  the source. I faintly remember looking into the css of the Iosevka website and googling the hex values but not finding anything and moving on.  
I tweaked some of the colours to improve the overall balance a little, and I'm pretty happy with the colours I added myself except for the greyish/greenish/blueish `#5688af` hack I used for the `PreProc` group.
The other colours in the palette form a coherent ensemble and I've found it pretty much impossible to find additional colours that felt right, both in terms of separation and brightness.

I worked on a light version for a while, but never felt like the colours were legible enough, especially as I use a fairly dark `#d4d6d7` background on my light terminal and pretty much dropped it. You can find the palette [here](https://github.com/neutaaaaan/monosvkem/blob/b6e434cd92e7a2187e456ec81bf530bf4dd63148/template/Monosvkem.colortemplate#L221) if you're interested.
