### ISSUE TITLE
Any plan to implement the light version of this theme?

### ISSUE THREAD

**Issue by subnut** [neutaaaaan/iosvkem#7]
I frequently switch dark and light using `set background`
In fact, that is the main reason I am still sticking to gruvbox

Will you implement this in the near future?
Thank you

**Comment by neutaaaaan** [comment]
No, my best-effort attempt had [readability issues](https://user-images.githubusercontent.com/35198994/84176036-5c4f9580-aa70-11ea-9f5e-8784a2acbe9a.jpg) and the 256c version looked [even worse](https://user-images.githubusercontent.com/35198994/84176529-10e9b700-aa71-11ea-896c-119f17f33f50.jpg).

You can find the palette [here](https://github.com/neutaaaaan/monosvkem/blob/master/template/Monosvkem.colortemplate#L214) but I'm not willing to ship or assume maintainership of something I won't use myself for fear of allowing those projects to rot on the side of the road.
